name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production
        run: npm run build

      - name: Serve build folder
        run: npx serve -s dist -l 5173 &

      - name: Wait for server
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npx cypress run
