name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build production
      - name: Build production
        run: npm run build

      # 5. Serve built app in background
      - name: Serve build folder
        run: npx serve -s build -l 5173 &

      # 6. Wait until server is ready
      - name: Wait for server
        run: npx wait-on http://localhost:5173

      # 7. Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
